name: Build App

on: push

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Configure Environment
      run: |
        wget -O premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        tar -xvzf premake5.tar.gz
        sudo mv premake5 /usr/bin/premake5
        premake5 gmake2
    - name: Build App
      run: |
        make config=release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-world
        path: bin/Release/